.TH FONULATOR "1" "August 2007" "fonulator" "User Commands"
.SH NAME
fonulator \- 
.B foneBRIDGE
configuration utility
.SH SYNOPSIS
.B fonulator 
[\fIOPTION\fR]... [\fIFILE\fR]
.SH DESCRIPTION
.\" Add any additional description here
.PP
Configure a 
.B foneBRIDGE
using the information in FILE (or the default /etc/redfone.conf).
.TP
\fB\-h\fR, \fB\-H\fR, \fB\-\-help\fR
display this help information
.TP
\fB\-v\fR, \fB\-\-verbose\fR
display verbose output
.TP
\fB\-q\fR, \fB\-\-query\fR
only query the foneRBIDGE for availability, do not configure
.TP
\fB\-V\fR, \fB\-\-version\fR
display version information
.TP
\fB\-C\fR, \fB\-\-configip\fR
configure IP addresses of the 
.B foneBRIDGE
interactively
.TP
\fBFILE\fR
configuration file (default: /etc/redfone.conf)
.PP
Exit status is 0 if OK, 1 if configuration failed. When using the query mode, exit status will be 0 if a 
.B foneBRIDGE
was detected and 1 otherwise.
.SH AUTHOR
Written by Brett Carrington.
.SH "REPORTING BUGS"
Report bugs to <support@red-fone.com>.
.SH COPYRIGHT
Copyright \(co 2007 Redfone Communications, LLC.
.br
There is NO WARRANTY for this software, to the extent permitted by law.
.SH "SEE ALSO"
The full documentation for
.B fonulator
and the 
.B foneBRIDGE 
is located at <http://www.red-fone.com>.
